### ISSUE TITLE
Replace Token Generation With random_compat or PHP7 random_bytes

### ISSUE THREAD

**Issue by soleo** [jobapis/jobs-to-mail#2]
There was a long discussion about  `openssl_random_pseudo_bytes()`. Ref https://github.com/paragonie/random_compat/issues/5

In PHP7,  @SammyK created a cryptographically secure version of generating random bytes https://secure.php.net/manual/en/function.random-bytes.php. `openssl_random_pseudo_bytes` should be used as the last resort for generating random bytes, not the first option. 

For earlier PHP version, https://packagist.org/packages/paragonie/random_compat would be a good replacement.

**Comment by karllhughes** [comment]
Thanks for the input. This is a good catch.

Since this project [requires PHP7](https://github.com/jobapis/jobs-to-mail/blob/master/composer.json#L11) we can probably just use the `random_bytes` function.

@soleo do you want to propose a PR? Otherwise I can work something out in the next couple weeks.

**Comment by soleo** [comment]
@karllhughes , sure. I can do it. It should be pretty easy change thanks to @SammyK
